import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "شروع کار",
      collapsed: false,
      items: [
        "getting-started/introduction",
        "getting-started/dashboard",
        "getting-started/glossary",
        "getting-started/faq",
        "getting-started/contributing",
      ],
    },
    {
      type: "category",
      label: "هوش مصنوعی",
      collapsed: false,
      items: [
        "ai/about",
        "ai/quickstart",
        "ai/api-keys",
        "ai/models",
        "ai/chat",
        "ai/usage-billing",
        "ai/api-reference",
      ],
    },
    {
      type: "category",
      label: "سرورهای ابری",
      collapsed: false,
      items: [
        "cloud-servers/about",
        "cloud-servers/create",
        "cloud-servers/access",
        "cloud-servers/manage",
        "cloud-servers/pricing",
      ],
    },
    {
      type: "category",
      label: "DNS",
      collapsed: false,
      items: [
        "dns/about",
        "dns/add-domain",
        "dns/records",
        "dns/troubleshooting",
      ],
    },
    {
      type: "category",
      label: "CDN",
      collapsed: false,
      items: [
        "cdn/about",
        "cdn/create-gateway",
        "cdn/locations",
        "cdn/waf",
      ],
    },
    {
      type: "category",
      label: "کیف پول",
      collapsed: false,
      items: [
        "wallet/about",
        "wallet/top-up",
        "wallet/transactions",
        "wallet/gift-code",
      ],
    },
    {
      type: "category",
      label: "حساب کاربری و پشتیبانی",
      collapsed: false,
      items: [
        "account/registration",
        "account/profile",
        "support/tickets",
      ],
    },
    {
      type: "category",
      label: "میرورها و مخزن‌ها",
      collapsed: false,
      items: [
        "mirrors/about",
        "mirrors/linux",
        "mirrors/languages",
        "mirrors/docker",
        "mirrors/devops",
        {
          type: "category",
          label: "راهنمای هر مخزن",
          collapsed: false,
          link: {
            type: "generated-index",
            title: "راهنمای هر مخزن",
            description:
              "راهنمای گام‌به‌گام تنظیم هر پکیج‌منیجر و توزیع روی میرور نوین کلاود: پیکربندی، بررسی، استفاده در CI و بازگشت.",
            slug: "/mirrors/guides",
          },
          items: [{ type: "autogenerated", dirName: "mirrors/guides" }],
        },
        "mirrors/all-repositories",
      ],
    },
  ],
};

export default sidebars;
