import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "شروع کار",
      collapsed: false,
      items: ["getting-started/introduction"],
    },
    {
      type: "category",
      label: "هوش مصنوعی",
      collapsed: false,
      items: [
        "ai/about",
        "ai/quickstart",
        "ai/api-keys",
        "ai/models",
        "ai/chat",
        "ai/usage-billing",
        "ai/api-reference",
      ],
    },
    {
      type: "category",
      label: "میرورها و مخزن‌ها",
      collapsed: false,
      items: [
        "mirrors/about",
        "mirrors/linux",
        "mirrors/languages",
        "mirrors/docker",
        "mirrors/devops",
        {
          type: "category",
          label: "راهنمای هر مخزن",
          collapsed: false,
          link: {
            type: "generated-index",
            title: "راهنمای هر مخزن",
            description:
              "راهنمای گام‌به‌گام تنظیم هر پکیج‌منیجر و توزیع روی میرور نوین کلاود: پیکربندی، بررسی، استفاده در CI و بازگشت.",
            slug: "/mirrors/guides",
          },
          items: [{ type: "autogenerated", dirName: "mirrors/guides" }],
        },
        "mirrors/all-repositories",
      ],
    },
  ],
};

export default sidebars;
