blank_issues_enabled: true
contact_links:
  - name: پشتیبانی فنی نوین کلاود
    url: https://console.novin.cloud/dashboard/tickets
    about: برای مشکلات فنی سرویس یا سوالات مربوط به حساب کاربری، تیکت ثبت کنید. این مخزن فقط برای مستندات است.
